version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rpm-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_EXTERNAL}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend-node/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: rpm-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@rpm.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  backend:
    build:
      context: ./backend-node
      dockerfile: Dockerfile
    container_name: rpm-backend
    restart: always
    depends_on:
      - db
    environment:
      - PORT=${BACKEND_PORT}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./storage:/app/storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: rpm-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  pgadmin_data:
